version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}


      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          paths: target/demo-java-spring-0.0.1-SNAPSHOT.jar
          
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo 'ˆˆˆThat should look familiarˆˆˆ'
